import Head from 'next/head'
import Link from 'next/link'
import PopularCard from '../components/PopularCard'

export default function Home() {
  return (
    <div className="container lg:mx-8 px-4 my-1 md:mx-4">
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon2.png" />
      </Head>
      <main className="main">
      <div className='justify-center items-center flex-col flex-1 p-[2rem] flex'>
          <img src="favicon2.png" className='h-40 w-40' />
        <h1 className='text-2xl font-semibold text-violet-700 md:text-5xl lg:text-6xl'>Hunting Coder Blog</h1>
        <p className='my-6 text-violet-700 text-sm lg:text-lg'>A blog for hunting coders by a hunting coder</p>
        <Link href='blog'>
        <button className='bg-violet-600 text-white px-7 py-3 rounded-2xl hover:bg-violet-700 hover:shadow-xl hover:shadow-violet-700'>Get Started →</button>
        </Link>
        <h2 className='my-10 lg:text-3xl text-lg bg-violet-600 text-white py-2 px-14 rounded-xl hover:shadow-xl hover:shadow-violet-700'>Popular Blogs</h2>
        </div>
        <div className='justify-center items-center flex'>
            <PopularCard/>
        </div>
      </main>
    </div>
  )
}
